pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
      - npm run lint
#      - npm run test # requires a neo4j service

  publish:
    image: plugins/docker
    registry: docker-registry.meringlab.org:5443
    repo: docker-registry.meringlab.org:5443/paxdb/orthology-api
    tags: 4.1.0
    auto_tag: false
    secrets: [ docker_username, docker_password ]
#    when:
#      event: deployment
#      environment: staging


# stable-master pattern
branches: master
